"""initial schema (snapshots, vol_points)

Revision ID: 9519fc0dc574
Revises: 
Create Date: 2026-07-08 20:16:51.496426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9519fc0dc574'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spot', sa.Float(), nullable=False),
    sa.Column('risk_free_rate', sa.Float(), nullable=False),
    sa.Column('dividend_yield', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'captured_at', name='uq_snapshot_ticker_ts')
    )
    op.create_index(op.f('ix_snapshots_captured_at'), 'snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_snapshots_ticker'), 'snapshots', ['ticker'], unique=False)
    op.create_table('vol_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('expiry', sa.String(length=10), nullable=False),
    sa.Column('tte', sa.Float(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=False),
    sa.Column('mid', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('open_interest', sa.Float(), nullable=False),
    sa.Column('log_moneyness', sa.Float(), nullable=False),
    sa.Column('implied_vol', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vol_points_snapshot_id'), 'vol_points', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vol_points_snapshot_id'), table_name='vol_points')
    op.drop_table('vol_points')
    op.drop_index(op.f('ix_snapshots_ticker'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_captured_at'), table_name='snapshots')
    op.drop_table('snapshots')
    # ### end Alembic commands ###
