"""add data_quality_reports

Revision ID: dd9a4dc0b0ef
Revises: 9519fc0dc574
Create Date: 2026-09-07 22:50:04.312777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9a4dc0b0ef'
down_revision: Union[str, Sequence[str], None] = '9519fc0dc574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('backfilled', sa.Boolean(), nullable=False),
    sa.Column('spot', sa.Float(), nullable=False),
    sa.Column('n_contracts_raw', sa.Integer(), nullable=True),
    sa.Column('n_kept', sa.Integer(), nullable=False),
    sa.Column('n_short_dte', sa.Integer(), nullable=True),
    sa.Column('n_otm_side', sa.Integer(), nullable=True),
    sa.Column('n_missing_price', sa.Integer(), nullable=True),
    sa.Column('n_non_positive_bid', sa.Integer(), nullable=True),
    sa.Column('n_crossed_market', sa.Integer(), nullable=True),
    sa.Column('n_low_open_interest', sa.Integer(), nullable=True),
    sa.Column('n_wide_spread', sa.Integer(), nullable=True),
    sa.Column('n_inversion_attempted', sa.Integer(), nullable=True),
    sa.Column('n_inversion_failed', sa.Integer(), nullable=True),
    sa.Column('inversion_failure_rate', sa.Float(), nullable=True),
    sa.Column('n_expiries', sa.Integer(), nullable=False),
    sa.Column('n_strikes', sa.Integer(), nullable=False),
    sa.Column('min_strike', sa.Float(), nullable=True),
    sa.Column('max_strike', sa.Float(), nullable=True),
    sa.Column('min_tte', sa.Float(), nullable=True),
    sa.Column('max_tte', sa.Float(), nullable=True),
    sa.Column('min_dte', sa.Integer(), nullable=True),
    sa.Column('max_dte', sa.Integer(), nullable=True),
    sa.Column('median_rel_spread', sa.Float(), nullable=True),
    sa.Column('p95_rel_spread', sa.Float(), nullable=True),
    sa.Column('max_rel_spread', sa.Float(), nullable=True),
    sa.Column('n_grid_cells', sa.Integer(), nullable=True),
    sa.Column('n_cells_observed', sa.Integer(), nullable=True),
    sa.Column('n_cells_extrapolated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_reports_snapshot_id'), 'data_quality_reports', ['snapshot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_quality_reports_snapshot_id'), table_name='data_quality_reports')
    op.drop_table('data_quality_reports')
    # ### end Alembic commands ###
